/* =========================================================================
   Banque de questions — 100 % issue des deux fiches du dossier docs/ :
     · « MCD · MLD · MPD — Petit Rayon de Soleil »
     · « Merise, UML et CI/CD — révision orale »
   Aucun contenu inventé : chaque explication reprend la fiche source.

   Types de questions :
     qcm    { q, a:[...], c:index, exp }
     multi  { q, a:[...], c:[index,...], exp }
     vf     { q, c:true|false, exp }
     ordre  { q, items:[... dans le bon ordre ...], exp }
     paires { q, pairs:[[gauche, droite], ...], exp }
     saisie { q, accept:[...], exp }
   Champ optionnel : code (bloc monospace affiché sous la question)
   ========================================================================= */

const COURSE = {
  title: 'Merise, UML & CI/CD',
  subtitle: 'Révision orale — Titre professionnel CDA',
  units: [
    /* ------------------------------------------------------------------ */
    {
      id: 'u1',
      title: 'Merise, la méthode',
      subtitle: 'Ce qu’est Merise et ce qu’elle n’est pas',
      color: '#f59e0b',
      icon: '📐',
      lessons: [
        {
          id: 'u1l1',
          title: 'C’est quoi Merise ?',
          icon: '📖',
          questions: [
            {
              t: 'qcm',
              q: 'Merise, c’est quoi ?',
              a: [
                'Un langage de programmation orienté objet',
                'Une méthode française d’analyse et de conception des systèmes d’information',
                'Un système de gestion de base de données',
                'Un framework de tests automatisés',
              ],
              c: 1,
              exp: 'Une méthode française d’analyse et de conception des systèmes d’information, née à la fin des années 1970.',
            },
            {
              t: 'qcm',
              q: 'Quel est le principe fondateur de Merise ?',
              a: [
                'Ne pas tout traiter en même temps : séparer les niveaux d’abstraction',
                'Écrire le SQL le plus tôt possible',
                'Documenter après le développement',
                'Automatiser toute la conception',
              ],
              c: 0,
              exp: 'Son principe : ne pas tout traiter en même temps, mais séparer les niveaux d’abstraction.',
            },
            {
              t: 'saisie',
              q: 'À quelle décennie Merise est-elle née ? (écris l’année ronde)',
              accept: ['1970', 'annees 1970', 'fin des annees 1970', '1970s', '70'],
              exp: 'Merise est née à la fin des années 1970.',
            },
            {
              t: 'ordre',
              q: 'Remets les trois modèles de données dans l’ordre de la démarche.',
              items: ['MCD — modèle conceptuel', 'MLD — modèle logique', 'MPD — modèle physique'],
              exp: 'Trois modèles successifs qui décrivent la même réalité à trois profondeurs : d’abord le métier, puis le relationnel, enfin le SGBD.',
            },
            {
              t: 'qcm',
              q: 'Merise décrit…',
              a: [
                'ce que le système fait (son comportement)',
                'ce que le système mémorise (les données)',
                'l’interface utilisateur',
                'la configuration du serveur',
              ],
              c: 1,
              exp: 'Merise décrit ce que le système mémorise : les données. UML décrit ce qu’il fait : le comportement.',
            },
            {
              t: 'vf',
              q: 'Merise et UML sont deux noms pour la même chose.',
              c: false,
              exp: 'Piège classique. Merise n’est pas UML, et l’inverse non plus. Le projet utilise les deux et il faut savoir dire lequel sert à quoi.',
            },
            {
              t: 'paires',
              q: 'Associe chaque méthode à son objet.',
              pairs: [
                ['Merise', 'Les données mémorisées'],
                ['UML', 'Le comportement du système'],
              ],
              exp: 'Merise décrit les données (MCD/MLD/MPD). UML décrit le comportement (cas d’utilisation, séquence).',
            },
            {
              t: 'qcm',
              q: 'Phrase à dire au jury pour ouvrir sur Merise :',
              a: [
                '« Merise est un vieux formalisme que j’ai utilisé par obligation. »',
                '« Merise est une méthode de conception qui sépare les niveaux d’abstraction : du modèle conceptuel au logique, puis au physique. Chaque niveau répond à une question différente. »',
                '« Merise m’a servi à dessiner ma base de données SQLite. »',
                '« Merise remplace UML dans mon projet. »',
              ],
              c: 1,
              exp: 'La formulation attendue insiste sur la séparation des niveaux et sur le fait que chaque niveau répond à une question différente.',
            },
          ],
        },
        {
          id: 'u1l2',
          title: 'Les trois niveaux',
          icon: '🧱',
          questions: [
            {
              t: 'qcm',
              q: 'Le MCD se situe à quel niveau ?',
              a: [
                'Niveau métier, indépendant de toute technologie',
                'Niveau relationnel, avec les clés étrangères',
                'Niveau SGBD, avec les types SQLite',
                'Niveau interface, avec les écrans',
              ],
              c: 0,
              exp: 'MCD = niveau métier, indépendant de toute technologie : entités, associations et cardinalités.',
            },
            {
              t: 'qcm',
              q: 'Le MLD, c’est…',
              a: [
                'la traduction relationnelle : tables, colonnes, clés',
                'le dessin des écrans',
                'le script SQL exécuté par le SGBD',
                'la liste des acteurs du système',
              ],
              c: 0,
              exp: 'Le MLD est la traduction relationnelle du MCD : relations et clés.',
            },
            {
              t: 'qcm',
              q: 'Le MPD, c’est…',
              a: [
                'un brouillon du MCD',
                'l’implémentation dans le SGBD choisi : types réels, contraintes, valeurs par défaut, règles de suppression',
                'la liste des routes de l’API',
                'le diagramme de séquence',
              ],
              c: 1,
              exp: 'MPD = implémentation SQLite : types réels, contraintes, valeurs par défaut et règles de suppression. C’est le niveau qui doit correspondre au code, ligne pour ligne.',
            },
            {
              t: 'vf',
              q: 'On trouve des types SQLite (INTEGER, TEXT) dès le MCD.',
              c: false,
              exp: 'Non : les types SGBD n’apparaissent qu’au MPD. Le MCD est indépendant de toute technologie.',
            },
            {
              t: 'multi',
              q: 'Que trouve-t-on au niveau MPD ? (plusieurs réponses)',
              a: [
                'Les types réels (INTEGER, TEXT)',
                'Les valeurs par défaut',
                'Les contraintes de domaine (CHECK)',
                'Les règles de suppression (CASCADE, SET NULL)',
                'Les cardinalités conceptuelles (1,N — N,N)',
              ],
              c: [0, 1, 2, 3],
              exp: 'Les cardinalités appartiennent au MCD. Le MPD ajoute types, valeurs par défaut, contraintes de domaine et règles de suppression.',
            },
            {
              t: 'qcm',
              q: 'À quel niveau se décide le comportement RGPD (CASCADE / SET NULL) ?',
              a: ['Au MCD', 'Au MLD', 'Au MPD', 'Dans le diagramme de cas d’utilisation'],
              c: 2,
              exp: 'C’est au MPD que se décide le comportement RGPD : CASCADE sur les favoris et les sessions, SET NULL sur propose_par.',
            },
            {
              t: 'vf',
              q: 'MCD, MLD et MPD décrivent la même réalité à trois profondeurs différentes.',
              c: true,
              exp: 'Exactement : d’abord le métier, puis le relationnel, enfin le SGBD.',
            },
          ],
        },
        {
          id: 'u1l3',
          title: 'Merise face au jury',
          icon: '🎤',
          questions: [
            {
              t: 'qcm',
              q: '« Pourquoi ne pas partir directement du SQL ? »',
              a: [
                'Parce que le SQL est trop long à écrire',
                'Parce que le SQL fige une implémentation avant d’avoir compris les règles de gestion',
                'Parce que SQLite ne supporte pas tout le SQL',
                'Parce que le jury l’interdit',
              ],
              c: 1,
              exp: 'Le SQL fige une implémentation. Le MCD permet de valider les règles de gestion avec quelqu’un qui ne code pas, et de changer d’avis sans réécrire de code.',
            },
            {
              t: 'qcm',
              q: 'Que dire du coût d’une erreur détectée au MCD ?',
              a: [
                'Il est très inférieur à celui d’une erreur détectée en production',
                'Il est équivalent',
                'Il est supérieur, car il faut tout redessiner',
                'Il est impossible à évaluer',
              ],
              c: 0,
              exp: 'Le coût d’une erreur détectée au MCD est très inférieur à celui d’une erreur détectée en production.',
            },
            {
              t: 'vf',
              q: 'Le MCD peut se discuter avec quelqu’un qui ne code pas ; le MPD, non.',
              c: true,
              exp: 'C’est l’argument central en faveur du MCD comme point de départ.',
            },
            {
              t: 'qcm',
              q: '« Merise n’est-elle pas dépassée ? »',
              a: [
                '« Oui, je ne l’utiliserais plus. »',
                '« Le formalisme est ancien, mais le raisonnement reste valable : séparer le métier du relationnel puis du physique. C’est ce que fait un ORM moderne avec ses entités et ses migrations. »',
                '« Non, tout le monde l’utilise encore. »',
                '« Elle est obligatoire pour le titre professionnel. »',
              ],
              c: 1,
              exp: 'La méthode a vieilli, pas le principe.',
            },
            {
              t: 'qcm',
              q: 'Quel outil moderne applique le même raisonnement que Merise ?',
              a: [
                'Un ORM, avec ses entités et ses migrations',
                'Un bundler JavaScript',
                'Un service worker',
                'Un linter',
              ],
              c: 0,
              exp: 'Un ORM moderne sépare lui aussi le métier (entités) du physique (migrations).',
            },
            {
              t: 'qcm',
              q: '« Pourquoi UML ET Merise ? »',
              a: [
                'Parce que le référentiel l’impose',
                'Parce qu’ils ne répondent pas à la même question : UML cadre les interactions, Merise structure ce que l’application mémorise',
                'Parce que Merise ne suffit pas techniquement',
                'Parce qu’UML est plus moderne',
              ],
              c: 1,
              exp: 'Les deux se complètent : le comportement d’un côté, la donnée de l’autre.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u2',
      title: 'La démarche, dans l’ordre',
      subtitle: 'La question la plus probable du jury',
      color: '#ef4444',
      icon: '🧭',
      lessons: [
        {
          id: 'u2l1',
          title: 'Les cinq étapes',
          icon: '1️⃣',
          questions: [
            {
              t: 'ordre',
              q: 'Remets la démarche du projet dans l’ordre.',
              items: [
                'Besoins et acteurs',
                'Cas d’utilisation UML',
                'Diagramme de séquence UML',
                'MCD, puis MLD, puis MPD',
                'Implémentation, tests, CI/CD, production',
              ],
              exp: 'Cinq étapes. On code seulement une fois que le quoi et le comment sont posés.',
            },
            {
              t: 'qcm',
              q: 'Par quoi commence-t-on ?',
              a: [
                'Par le MCD',
                'Par les besoins et les acteurs : qui fait quoi, quelles règles métier, quelles contraintes',
                'Par le choix du SGBD',
                'Par la configuration de la CI',
              ],
              c: 1,
              exp: 'Étape 1 : besoins et acteurs. Rien de technique.',
            },
            {
              t: 'qcm',
              q: 'Quelle étape fixe le périmètre du projet ?',
              a: [
                'Le diagramme de cas d’utilisation UML',
                'Le MPD',
                'Le diagramme de séquence',
                'Le pipeline CI',
              ],
              c: 0,
              exp: 'Cas d’utilisation UML : quelles fonctionnalités, pour quel rôle. Il fixe le périmètre.',
            },
            {
              t: 'qcm',
              q: 'À quoi sert le diagramme de séquence dans cette démarche ?',
              a: [
                'À lister les acteurs',
                'À dérouler le scénario critique dans le temps entre les composants',
                'À décrire les tables',
                'À documenter le déploiement',
              ],
              c: 1,
              exp: 'Étape 3 : le scénario critique, déroulé dans le temps entre les composants.',
            },
            {
              t: 'vf',
              q: 'Dans cette démarche, on modélise les données avant les interactions.',
              c: false,
              exp: 'Non : UML (cas d’utilisation puis séquence) vient avant Merise (MCD → MLD → MPD).',
            },
            {
              t: 'qcm',
              q: 'Quand commence-t-on à coder ?',
              a: [
                'Dès l’étape 1, pour gagner du temps',
                'Seulement une fois que le quoi et le comment sont posés',
                'En parallèle du MCD',
                'Après la mise en production',
              ],
              c: 1,
              exp: 'Étape 5 : implémentation, tests, CI/CD, production — une fois le quoi et le comment posés.',
            },
            {
              t: 'qcm',
              q: 'La réponse courte à « dans quel ordre ? » :',
              a: [
                '« Je commence par la base de données, puis je code l’API, puis le front. »',
                '« Je commence par les besoins et les acteurs. Je modélise les interactions avec UML. Ensuite je modélise les données avec Merise, du MCD au MPD, avant d’implémenter la base et de tester le scénario le plus important. »',
                '« Je suis une méthode agile, donc je ne fixe pas d’ordre. »',
                '« Je commence par le diagramme de séquence, c’est le plus parlant. »',
              ],
              c: 1,
              exp: 'C’est la réponse courte à mémoriser telle quelle.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u3',
      title: 'Le MCD',
      subtitle: 'Entités, associations, cardinalités',
      color: '#22c55e',
      icon: '🫧',
      lessons: [
        {
          id: 'u3l1',
          title: 'Entités et associations',
          icon: '🔗',
          questions: [
            {
              t: 'multi',
              q: 'Quelles sont les entités du MCD de Petit Rayon de Soleil ?',
              a: ['UTILISATEUR', 'MESSAGE', 'SESSION', 'FAVORIS', 'ADMINISTRATEUR'],
              c: [0, 1, 2],
              exp: 'Trois entités : UTILISATEUR, MESSAGE, SESSION. « Met en favori » est une association, pas encore une table.',
            },
            {
              t: 'qcm',
              q: 'Au niveau MCD, « met en favori » est…',
              a: [
                'une table de liaison',
                'une association N,N — elle n’est pas encore une table',
                'une clé étrangère',
                'une contrainte CHECK',
              ],
              c: 1,
              exp: 'Au MCD c’est une association N,N. Elle ne devient une table qu’au MLD.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la cardinalité de l’association « propose » (utilisateur → message) ?',
              a: ['1,1', '1,N', 'N,N', '0,1'],
              c: 1,
              exp: '« Propose » est une association 1,N : un utilisateur propose plusieurs messages.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la cardinalité de l’association « possède » (utilisateur → session) ?',
              a: ['1,N', 'N,N', '1,1', '0,0'],
              c: 0,
              exp: '« Possède » est également une association 1,N.',
            },
            {
              t: 'vf',
              q: 'Le MCD contient des clés étrangères.',
              c: false,
              exp: 'Non : les clés étrangères apparaissent au MLD. Le MCD décrit entités, associations et cardinalités.',
            },
            {
              t: 'multi',
              q: 'Quels attributs porte l’entité UTILISATEUR dans le MCD ?',
              a: ['nom', 'email', 'role', 'jeton', 'contenu'],
              c: [0, 1, 2],
              exp: 'UTILISATEUR : nom, email, role. Le jeton appartient à SESSION, le contenu à MESSAGE.',
            },
            {
              t: 'paires',
              q: 'Associe chaque attribut du MCD à son entité.',
              pairs: [
                ['contenu', 'MESSAGE'],
                ['statut', 'MESSAGE'],
                ['jeton', 'SESSION'],
                ['email', 'UTILISATEUR'],
              ],
              exp: 'MESSAGE porte contenu, statut et date_creation ; SESSION porte jeton et date_creation.',
            },
            {
              t: 'qcm',
              q: 'À quoi sert le MCD dans la discussion avec le métier ?',
              a: [
                'Il exprime le besoin métier sans subir les choix techniques',
                'Il montre la structure des fichiers du projet',
                'Il documente les routes de l’API',
                'Il liste les dépendances npm',
              ],
              c: 0,
              exp: 'Il exprime le besoin métier sans subir les choix techniques — c’est pourquoi on commence par lui.',
            },
          ],
        },
        {
          id: 'u3l2',
          title: 'Le correctif « status »',
          icon: '🩹',
          questions: [
            {
              t: 'qcm',
              q: 'Quelle correction a été apportée aux trois diagrammes précédents ?',
              a: [
                'L’attribut approved (booléen) est remplacé par status (texte, trois états)',
                'La table sessions a été supprimée',
                'L’entité UTILISATEUR a été renommée MEMBRE',
                'Les cardinalités ont été inversées',
              ],
              c: 0,
              exp: 'Les diagrammes affichaient un champ approved booléen qui n’existe pas dans le code. La vraie colonne est status.',
            },
            {
              t: 'qcm',
              q: 'Pourquoi un booléen ne peut-il pas représenter l’état d’un message ?',
              a: [
                'Parce que SQLite n’a pas de type booléen',
                'Parce qu’il code « validé / pas validé » alors que la règle métier distingue en attente, validé et rejeté',
                'Parce qu’il prend trop de place',
                'Parce qu’il empêche les requêtes paramétrées',
              ],
              c: 1,
              exp: 'Un booléen ne peut pas représenter le rejet : il ne distingue pas « en attente » de « rejeté ».',
            },
            {
              t: 'multi',
              q: 'Quels sont les trois états contrôlés par la contrainte CHECK ?',
              a: ['pending', 'approved', 'rejected', 'draft', 'archived'],
              c: [0, 1, 2],
              exp: 'CHECK (status IN (\'pending\', \'approved\', \'rejected\')).',
            },
            {
              t: 'saisie',
              q: 'Quel est le nom réel de la colonne dans db.js ?',
              accept: ['status'],
              exp: 'La vraie colonne est status, avec trois valeurs. Le champ approved n’existe pas.',
            },
            {
              t: 'vf',
              q: 'Le champ approved existe bien dans db.js.',
              c: false,
              exp: 'Non. C’est précisément l’erreur corrigée : approved n’existe pas, c’est status.',
            },
            {
              t: 'qcm',
              q: 'Quel autre correctif a été apporté au modèle ?',
              a: [
                'La table favoris est renommée au singulier français, conforme au CREATE TABLE réel',
                'La table users est renommée utilisateurs',
                'La table sessions perd sa clé primaire',
                'La colonne content devient contenu',
              ],
              c: 0,
              exp: 'La table favoris est nommée au singulier français, conformément au CREATE TABLE réel.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u4',
      title: 'Le MLD',
      subtitle: 'Tables, clés, table de liaison',
      color: '#06b6d4',
      icon: '🗝️',
      lessons: [
        {
          id: 'u4l1',
          title: 'Traduction relationnelle',
          icon: '🔁',
          questions: [
            {
              t: 'multi',
              q: 'Quelles colonnes porte la table USERS au MLD ?',
              a: ['id (PK)', 'name', 'email (UK)', 'password_hash', 'role', 'created_at', 'token'],
              c: [0, 1, 2, 3, 4, 5],
              exp: 'USERS : id (PK), name, email (UK), password_hash, role, created_at. Le token appartient à SESSIONS.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la clé primaire de la table SESSIONS ?',
              a: ['user_id', 'token', 'id', 'created_at'],
              c: 1,
              exp: 'SESSIONS : token en clé primaire, user_id en clé étrangère, created_at.',
            },
            {
              t: 'qcm',
              q: 'Quelle colonne de MESSAGES est une clé étrangère ?',
              a: ['content', 'status', 'propose_par', 'created_at'],
              c: 2,
              exp: 'propose_par est la clé étrangère qui référence users(id) : c’est la traduction de l’association « propose ».',
            },
            {
              t: 'qcm',
              q: 'Sur quelle colonne porte la contrainte d’unicité (UK) dans USERS ?',
              a: ['name', 'email', 'role', 'password_hash'],
              c: 1,
              exp: 'email est unique : un compte par adresse.',
            },
            {
              t: 'paires',
              q: 'Associe chaque sigle à sa signification.',
              pairs: [
                ['PK', 'Clé primaire'],
                ['FK', 'Clé étrangère'],
                ['UK', 'Contrainte d’unicité'],
              ],
              exp: 'PK identifie la ligne, FK référence une autre table, UK garantit qu’une valeur n’apparaît qu’une fois.',
            },
            {
              t: 'vf',
              q: 'Une association N,N peut se traduire par une simple clé étrangère.',
              c: false,
              exp: 'Non : une association N,N ne peut pas se réduire à une clé étrangère, elle donne naissance à une table de liaison.',
            },
            {
              t: 'qcm',
              q: 'Quelles valeurs peut prendre la colonne status au MLD ?',
              a: [
                'true | false',
                'pending | approved | rejected',
                '0 | 1 | 2',
                'draft | published',
              ],
              c: 1,
              exp: 'status : pending | approved | rejected.',
            },
            {
              t: 'qcm',
              q: 'Le MLD, contrairement au MCD…',
              a: [
                'ne montre plus les colonnes',
                'fait apparaître les tables, les clés primaires et les clés étrangères',
                'choisit déjà le SGBD',
                'décrit les écrans',
              ],
              c: 1,
              exp: 'Le MLD est la traduction relationnelle : chaque entité devient une table, l’identifiant devient la clé primaire.',
            },
          ],
        },
        {
          id: 'u4l2',
          title: 'La table de liaison',
          icon: '🧷',
          questions: [
            {
              t: 'qcm',
              q: 'Que devient l’association N,N « met en favori » au MLD ?',
              a: [
                'Une colonne dans users',
                'Une table de liaison favoris',
                'Une vue SQL',
                'Un index',
              ],
              c: 1,
              exp: 'L’association N,N devient une table de liaison favoris portant les deux clés.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la clé primaire de la table favoris ?',
              a: [
                'user_id seul',
                'message_id seul',
                'Le couple (user_id, message_id)',
                'Un id auto-incrémenté',
              ],
              c: 2,
              exp: 'La clé primaire est le couple (user_id, message_id).',
            },
            {
              t: 'qcm',
              q: 'Que garantit cette clé primaire composite ?',
              a: [
                'Qu’un message ne peut avoir qu’un seul favori',
                'Qu’un utilisateur ne peut pas mettre deux fois le même message en favori',
                'Que les favoris sont triés',
                'Que la suppression est en cascade',
              ],
              c: 1,
              exp: 'Elle garantit qu’un utilisateur ne peut pas mettre deux fois le même message en favori.',
            },
            {
              t: 'multi',
              q: 'Quelles colonnes composent la table favoris ?',
              a: ['user_id', 'message_id', 'created_at', 'id', 'status'],
              c: [0, 1],
              exp: 'favoris ne porte que les deux clés : user_id et message_id, toutes deux PK et FK.',
            },
            {
              t: 'vf',
              q: 'Dans la table favoris, user_id et message_id sont à la fois clé primaire et clé étrangère.',
              c: true,
              exp: 'PK_FK pour les deux colonnes : elles forment la clé primaire et référencent chacune leur table.',
            },
            {
              t: 'qcm',
              q: 'Comment expliquer l’origine de la table favoris au jury ?',
              a: [
                '« Je l’ai ajoutée pour des raisons de performance. »',
                '« Elle vient de la règle de passage : une association N,N ne peut pas se réduire à une clé étrangère, elle donne naissance à une table de liaison portant les deux clés. »',
                '« C’est une contrainte de SQLite. »',
                '« C’est une table technique générée par l’ORM. »',
              ],
              c: 1,
              exp: 'C’est une règle de passage, pas une intuition.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u5',
      title: 'Le MPD',
      subtitle: 'SQLite, contraintes et RGPD',
      color: '#3b82f6',
      icon: '🗄️',
      lessons: [
        {
          id: 'u5l1',
          title: 'Types et contraintes',
          icon: '🔤',
          questions: [
            {
              t: 'qcm',
              q: 'Quel est le type exact de users.id ?',
              a: [
                'INTEGER PRIMARY KEY AUTOINCREMENT',
                'TEXT PRIMARY KEY',
                'INTEGER NOT NULL',
                'SERIAL',
              ],
              c: 0,
              exp: 'INTEGER PK AUTOINCREMENT, comme messages.id.',
            },
            {
              t: 'qcm',
              q: 'Quelles contraintes portent sur users.email ?',
              a: ['TEXT NOT NULL', 'TEXT NOT NULL UNIQUE', 'TEXT UNIQUE', 'TEXT PRIMARY KEY'],
              c: 1,
              exp: 'email : TEXT NOT NULL UNIQUE.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la valeur par défaut de users.role ?',
              a: ["'admin'", "'user'", 'NULL', "'member'"],
              c: 1,
              exp: "role : TEXT NOT NULL DEFAULT 'user'.",
            },
            {
              t: 'qcm',
              q: 'Quelle est la valeur par défaut des colonnes created_at ?',
              a: ['NULL', "CURRENT_TIMESTAMP", "datetime('now')", '0'],
              c: 2,
              exp: "created_at : TEXT NOT NULL DEFAULT datetime('now'), dans les trois tables concernées.",
            },
            {
              t: 'qcm',
              q: 'Quelles contraintes portent sur messages.status ?',
              a: [
                "NOT NULL uniquement",
                "NOT NULL DEFAULT 'pending' + CHECK sur trois valeurs",
                "UNIQUE + CHECK",
                "PRIMARY KEY",
              ],
              c: 1,
              exp: "status : TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')).",
            },
            {
              t: 'qcm',
              q: 'Quel est le type de sessions.token ?',
              a: ['TEXT PRIMARY KEY', 'INTEGER PRIMARY KEY', 'TEXT NOT NULL UNIQUE', 'BLOB'],
              c: 0,
              exp: 'sessions : token TEXT PRIMARY KEY.',
            },
            {
              t: 'vf',
              q: 'Le MPD est le niveau qui doit correspondre au code, ligne pour ligne.',
              c: true,
              exp: 'C’est la formule de la fiche : le MPD doit correspondre au code, ligne pour ligne.',
            },
            {
              t: 'saisie',
              q: 'Quelle commande npm exécute le schéma décrit par le MPD ?',
              accept: ['npm run init-db', 'init-db', 'npm run initdb'],
              exp: 'Les diagrammes ont été vérifiés contre db.js — schéma exécuté par npm run init-db.',
            },
          ],
        },
        {
          id: 'u5l2',
          title: 'Suppressions et RGPD',
          icon: '🧹',
          questions: [
            {
              t: 'qcm',
              q: 'Quelle règle de suppression porte messages.propose_par ?',
              a: ['ON DELETE CASCADE', 'ON DELETE SET NULL', 'ON DELETE RESTRICT', 'Aucune'],
              c: 1,
              exp: 'FOREIGN KEY (propose_par) REFERENCES users(id) ON DELETE SET NULL.',
            },
            {
              t: 'qcm',
              q: 'Quel est l’effet RGPD de ce SET NULL ?',
              a: [
                'Il supprime les messages avec le compte',
                'Il conserve les messages publiés en les anonymisant',
                'Il bloque la suppression du compte',
                'Il archive les messages',
              ],
              c: 1,
              exp: 'SET NULL sur propose_par conserve les messages publiés en les anonymisant.',
            },
            {
              t: 'multi',
              q: 'Quelles données sont effacées avec le compte grâce à ON DELETE CASCADE ?',
              a: ['Les favoris', 'Les sessions', 'Les messages publiés', 'Les comptes administrateurs'],
              c: [0, 1],
              exp: 'CASCADE sur les favoris et les sessions les efface avec le compte.',
            },
            {
              t: 'qcm',
              q: 'Quelle règle porte favoris.user_id ?',
              a: [
                'INTEGER PK+FK → users(id) ON DELETE CASCADE',
                'INTEGER FK → users(id) ON DELETE SET NULL',
                'TEXT PK',
                'INTEGER NOT NULL sans FK',
              ],
              c: 0,
              exp: 'favoris.user_id : INTEGER PK+FK vers users(id) ON DELETE CASCADE. Idem pour message_id vers messages(id).',
            },
            {
              t: 'qcm',
              q: 'Quelle règle porte sessions.user_id ?',
              a: [
                'INTEGER NOT NULL FK → users(id) ON DELETE CASCADE',
                'INTEGER FK → users(id) ON DELETE SET NULL',
                'TEXT PRIMARY KEY',
                'Aucune contrainte',
              ],
              c: 0,
              exp: 'sessions.user_id : INTEGER NOT NULL FK vers users(id) ON DELETE CASCADE.',
            },
            {
              t: 'paires',
              q: 'Associe chaque clé étrangère à sa règle de suppression.',
              pairs: [
                ['messages.propose_par', 'SET NULL'],
                ['favoris.user_id', 'CASCADE'],
                ['sessions.user_id', 'CASCADE'],
              ],
              exp: 'CASCADE efface avec le compte ; SET NULL conserve en anonymisant.',
            },
            {
              t: 'qcm',
              q: 'Comment présenter cet arbitrage au jury ?',
              a: [
                '« J’ai mis CASCADE partout pour simplifier. »',
                '« C’est au MPD que se décide le comportement RGPD : CASCADE efface les données rattachées au compte, SET NULL conserve les messages publiés en les anonymisant. »',
                '« SQLite impose ces règles. »',
                '« Je supprime tout manuellement dans le code. »',
              ],
              c: 1,
              exp: 'L’arbitrage est explicite et assumé : ce qui est effacé, ce qui est anonymisé.',
            },
          ],
        },
        {
          id: 'u5l3',
          title: 'Le DDL par cœur',
          icon: '⌨️',
          questions: [
            {
              t: 'qcm',
              q: 'Complète le DDL de la table messages :',
              code: "CREATE TABLE IF NOT EXISTS messages (\n  id         INTEGER PRIMARY KEY AUTOINCREMENT,\n  content    TEXT NOT NULL,\n  status     TEXT NOT NULL DEFAULT 'pending'\n             ______________________________________,\n  propose_par INTEGER,\n  created_at TEXT NOT NULL DEFAULT (datetime('now')),\n  FOREIGN KEY (propose_par) REFERENCES users(id) ON DELETE SET NULL\n);",
              a: [
                "CHECK (status IN ('pending', 'approved', 'rejected'))",
                "UNIQUE (status)",
                "REFERENCES status(id)",
                "COLLATE NOCASE",
              ],
              c: 0,
              exp: 'La contrainte de domaine CHECK verrouille les trois valeurs autorisées.',
            },
            {
              t: 'qcm',
              q: 'Complète le DDL de la table favoris :',
              code: 'CREATE TABLE IF NOT EXISTS favoris (\n  user_id    INTEGER NOT NULL,\n  message_id INTEGER NOT NULL,\n  ________________________________,\n  FOREIGN KEY (user_id)    REFERENCES users(id)    ON DELETE CASCADE,\n  FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE\n);',
              a: [
                'PRIMARY KEY (user_id, message_id)',
                'UNIQUE (user_id)',
                'PRIMARY KEY (user_id)',
                'CHECK (user_id > 0)',
              ],
              c: 0,
              exp: 'PRIMARY KEY (user_id, message_id) : la clé composite garantit l’unicité du couple.',
            },
            {
              t: 'qcm',
              q: 'Que signifie IF NOT EXISTS dans CREATE TABLE IF NOT EXISTS ?',
              a: [
                'La table est recréée à chaque exécution',
                'La table n’est créée que si elle n’existe pas déjà : le script est rejouable',
                'La table est temporaire',
                'La table est créée en mémoire',
              ],
              c: 1,
              exp: 'Le DDL réel de db.js utilise IF NOT EXISTS : le script d’initialisation peut être relancé sans casser la base.',
            },
            {
              t: 'multi',
              q: 'Quelles colonnes composent la table messages ?',
              a: ['id', 'content', 'status', 'propose_par', 'created_at', 'approved', 'title'],
              c: [0, 1, 2, 3, 4],
              exp: 'Cinq colonnes. approved n’existe pas — c’est l’erreur des anciens diagrammes.',
            },
            {
              t: 'vf',
              q: 'created_at est stocké en TEXT dans ce schéma SQLite.',
              c: true,
              exp: "created_at TEXT NOT NULL DEFAULT (datetime('now')).",
            },
            {
              t: 'qcm',
              q: 'Contre quels fichiers les diagrammes ont-ils été vérifiés ?',
              a: [
                'db.js, server.js et .github/workflows/ci.yml',
                'package.json seulement',
                'Le dossier public/',
                'Aucun : ils ont été dessinés a priori',
              ],
              c: 0,
              exp: 'Contenu vérifié contre db.js, server.js et .github/workflows/ci.yml.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u6',
      title: 'Les règles de passage',
      subtitle: 'Ce que le jury attend derrière « dans quel ordre ? »',
      color: '#8b5cf6',
      icon: '➡️',
      lessons: [
        {
          id: 'u6l1',
          title: 'MCD → MLD',
          icon: '🔀',
          questions: [
            {
              t: 'qcm',
              q: 'Que devient chaque entité du MCD ?',
              a: ['Une colonne', 'Une table', 'Une vue', 'Un index'],
              c: 1,
              exp: 'Chaque entité devient une table, ses attributs deviennent des colonnes, son identifiant devient la clé primaire.',
            },
            {
              t: 'qcm',
              q: 'Comment se traduit une association 1,N ?',
              a: [
                'Par une table de liaison',
                'Par une clé étrangère du côté N',
                'Par une contrainte CHECK',
                'Par une colonne booléenne',
              ],
              c: 1,
              exp: 'Une association 1,N se traduit par une clé étrangère du côté N.',
            },
            {
              t: 'qcm',
              q: 'Où l’association « propose » place-t-elle sa clé étrangère ?',
              a: [
                'propose_par dans messages',
                'message_id dans users',
                'user_id dans favoris',
                'token dans sessions',
              ],
              c: 0,
              exp: '« Propose » place propose_par dans messages : la clé étrangère va du côté N.',
            },
            {
              t: 'qcm',
              q: 'Comment se traduit une association N,N ?',
              a: [
                'Par une clé étrangère dans chacune des deux tables',
                'Par une table de liaison portant les deux clés',
                'Par une contrainte UNIQUE',
                'Elle ne se traduit pas',
              ],
              c: 1,
              exp: 'Elle ne peut pas se réduire à une clé étrangère : elle donne naissance à une table de liaison portant les deux clés — c’est l’origine de favoris.',
            },
            {
              t: 'paires',
              q: 'Associe chaque élément du MCD à sa traduction au MLD.',
              pairs: [
                ['Entité', 'Table'],
                ['Attribut', 'Colonne'],
                ['Identifiant', 'Clé primaire'],
                ['Association N,N', 'Table de liaison'],
              ],
              exp: 'Ce sont les règles de passage MCD → MLD, à réciter dans cet ordre.',
            },
            {
              t: 'vf',
              q: 'Chaque niveau se déduit du précédent par des règles, pas par intuition.',
              c: true,
              exp: 'C’est exactement la phrase à placer quand le jury demande « dans quel ordre ? ».',
            },
            {
              t: 'qcm',
              q: 'D’où vient la table favoris ?',
              a: [
                'D’un besoin de performance',
                'De la traduction de l’association N,N « met en favori »',
                'D’une contrainte de SQLite',
                'Du diagramme de séquence',
              ],
              c: 1,
              exp: 'C’est l’origine de favoris : la règle de passage sur les associations N,N.',
            },
          ],
        },
        {
          id: 'u6l2',
          title: 'MLD → MPD',
          icon: '⚙️',
          questions: [
            {
              t: 'qcm',
              q: 'Que fait-on en premier au passage MLD → MPD ?',
              a: [
                'On choisit le SGBD',
                'On dessine les cardinalités',
                'On écrit les tests',
                'On rédige les user stories',
              ],
              c: 0,
              exp: 'On choisit le SGBD et on descend dans le concret.',
            },
            {
              t: 'multi',
              q: 'Qu’ajoute-t-on concrètement au MPD ?',
              a: [
                'Les types SQLite (INTEGER, TEXT)',
                'Les valeurs par défaut',
                'Les contraintes de domaine (CHECK sur status)',
                'Les règles de suppression',
                'Les acteurs du système',
              ],
              c: [0, 1, 2, 3],
              exp: 'Les acteurs relèvent d’UML, pas du MPD.',
            },
            {
              t: 'vf',
              q: 'Le choix du SGBD intervient dès le MLD.',
              c: false,
              exp: 'Non : le MLD reste relationnel générique. Le SGBD est choisi au passage vers le MPD.',
            },
            {
              t: 'qcm',
              q: 'Quel type logique devient INTEGER en SQLite ?',
              a: ['Le texte libre', 'Les identifiants et clés numériques', 'Les dates', 'Les booléens uniquement'],
              c: 1,
              exp: 'Les types logiques deviennent des types SQLite : INTEGER pour les identifiants et clés, TEXT pour le reste dans ce schéma.',
            },
            {
              t: 'ordre',
              q: 'Remets les opérations du passage MLD → MPD dans l’ordre.',
              items: [
                'Choisir le SGBD',
                'Traduire les types logiques en types SQLite',
                'Ajouter les valeurs par défaut',
                'Ajouter les contraintes de domaine (CHECK)',
                'Définir les règles de suppression (CASCADE / SET NULL)',
              ],
              exp: 'On descend dans le concret étape par étape ; les règles de suppression closent le passage, et c’est là que se décide le comportement RGPD.',
            },
            {
              t: 'qcm',
              q: 'Pourquoi le MPD est-il le niveau le plus exposé en soutenance ?',
              a: [
                'Parce qu’il est le plus joli à dessiner',
                'Parce qu’il doit correspondre au code ligne pour ligne : un écart se voit immédiatement',
                'Parce qu’il est obligatoire dans le référentiel',
                'Parce qu’il remplace la documentation',
              ],
              c: 1,
              exp: 'C’est le niveau qui doit correspondre au code, ligne pour ligne — d’où la correction approved → status.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u7',
      title: 'UML — cas d’utilisation',
      subtitle: 'Qui peut faire quoi',
      color: '#ec4899',
      icon: '🎭',
      lessons: [
        {
          id: 'u7l1',
          title: 'Qui peut faire quoi',
          icon: '❓',
          questions: [
            {
              t: 'qcm',
              q: 'À quelle question répond le diagramme de cas d’utilisation ?',
              a: [
                'Dans quel ordre les composants échangent-ils ?',
                'Qui peut faire quoi ?',
                'Comment les données sont-elles stockées ?',
                'Combien de temps prend une requête ?',
              ],
              c: 1,
              exp: 'Il répond à une seule question : qui peut faire quoi ?',
            },
            {
              t: 'qcm',
              q: 'Où se situent les acteurs par rapport au système ?',
              a: [
                'À l’intérieur du système',
                'À l’extérieur du système',
                'Dans la couche métier',
                'Dans la base de données',
              ],
              c: 1,
              exp: 'Les acteurs sont à l’extérieur du système : visiteur, utilisateur inscrit, administrateur.',
            },
            {
              t: 'qcm',
              q: 'Que représentent les bulles du diagramme ?',
              a: [
                'Des écrans de l’application',
                'Des routes de l’API',
                'Des services rendus',
                'Des tables de la base',
              ],
              c: 2,
              exp: 'Les bulles sont des services rendus, jamais des écrans ni des routes.',
            },
            {
              t: 'vf',
              q: 'Une bulle nommée « POST /api/messages » est une formulation correcte de cas d’utilisation.',
              c: false,
              exp: 'Non : si une bulle s’appelle POST /api/messages, c’est un diagramme technique, pas un use case. La bonne formulation est « Proposer un message ».',
            },
            {
              t: 'saisie',
              q: 'Reformule « POST /api/messages » en cas d’utilisation correct.',
              accept: [
                'proposer un message',
                'proposer message',
                'proposer un contenu',
              ],
              exp: 'La bonne formulation est « Proposer un message » : un service rendu, pas une route.',
            },
            {
              t: 'multi',
              q: 'Que ne doit-on jamais mettre dans un cas d’utilisation ?',
              a: ['Des tables', 'Des routes', 'Des classes', 'Des acteurs', 'Des services rendus'],
              c: [0, 1, 2],
              exp: 'Ne jamais mettre de tables, de routes ou de classes dans un cas d’utilisation.',
            },
            {
              t: 'qcm',
              q: 'À quoi sert concrètement ce diagramme dans le projet ?',
              a: [
                'À vérifier la couverture des besoins et les droits par rôle',
                'À optimiser les requêtes SQL',
                'À décrire le pipeline CI',
                'À dimensionner l’hébergement',
              ],
              c: 0,
              exp: 'Il sert à vérifier la couverture des besoins et les droits par rôle.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la portée du diagramme de cas d’utilisation ?',
              a: [
                'Un seul scénario, dans le temps',
                'Tout le système, de manière fonctionnelle et statique',
                'La couche données uniquement',
                'Le déploiement',
              ],
              c: 1,
              exp: 'Portée : tout le système. Vue fonctionnelle et statique, acteurs et services.',
            },
          ],
        },
        {
          id: 'u7l2',
          title: 'Acteurs et héritages',
          icon: '👥',
          questions: [
            {
              t: 'multi',
              q: 'Quels cas d’utilisation appartiennent au visiteur non connecté ?',
              a: [
                'Consulter les messages',
                'Voir le message du jour',
                'S’inscrire',
                'Se connecter',
                'Gérer ses favoris',
              ],
              c: [0, 1, 2, 3],
              exp: 'Gérer ses favoris appartient à l’utilisateur inscrit.',
            },
            {
              t: 'qcm',
              q: 'Pourquoi « s’inscrire » et « se connecter » appartiennent-ils au visiteur ?',
              a: [
                'Par convention UML',
                'Parce qu’on n’est pas encore inscrit au moment où l’on s’inscrit',
                'Parce que l’administrateur les gère',
                'Parce que ce sont des routes publiques',
              ],
              c: 1,
              exp: 'On n’est pas encore inscrit au moment où l’on s’inscrit : ces cas appartiennent au visiteur, pas au membre.',
            },
            {
              t: 'multi',
              q: 'Quels cas d’utilisation appartiennent à l’utilisateur inscrit ?',
              a: [
                'Proposer un message',
                'Gérer ses favoris',
                'Gérer / supprimer son compte (RGPD)',
                'Approuver une proposition',
              ],
              c: [0, 1, 2],
              exp: 'Approuver ou rejeter une proposition appartient à l’administrateur.',
            },
            {
              t: 'qcm',
              q: 'Quel cas d’utilisation est propre à l’administrateur ?',
              a: [
                'Consulter les messages',
                'Approuver / rejeter une proposition',
                'Gérer ses favoris',
                'Voir le message du jour',
              ],
              c: 1,
              exp: 'L’administrateur approuve ou rejette une proposition.',
            },
            {
              t: 'qcm',
              q: 'Comment fonctionnent les héritages entre acteurs ?',
              a: [
                'Ils sont indépendants',
                'Ils se cumulent : l’utilisateur inscrit peut tout ce que fait un visiteur, et l’administrateur tout ce que fait un utilisateur inscrit',
                'L’administrateur n’hérite de rien',
                'Le visiteur hérite du membre',
              ],
              c: 1,
              exp: 'Les héritages se cumulent, du visiteur vers l’administrateur.',
            },
            {
              t: 'ordre',
              q: 'Range les acteurs du moins au plus doté de droits.',
              items: ['Visiteur non connecté', 'Utilisateur inscrit', 'Administrateur'],
              exp: 'Chaîne d’héritage : l’administrateur peut tout ce que fait un utilisateur inscrit, qui peut tout ce que fait un visiteur.',
            },
            {
              t: 'vf',
              q: 'L’administrateur peut consulter les messages sans que ce cas soit relié directement à lui.',
              c: true,
              exp: 'Oui : il en hérite via l’utilisateur inscrit, qui en hérite du visiteur.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8',
      title: 'UML — diagramme de séquence',
      subtitle: 'Le scénario le plus représentatif',
      color: '#f43f5e',
      icon: '⏱️',
      lessons: [
        {
          id: 'u8l1',
          title: 'Le scénario critique',
          icon: '🎬',
          questions: [
            {
              t: 'qcm',
              q: 'À quelle question répond le diagramme de séquence ?',
              a: [
                'Qui peut faire quoi ?',
                'Dans quel ordre les composants échangent-ils ?',
                'Quelles données sont mémorisées ?',
                'Quel est le coût d’hébergement ?',
              ],
              c: 1,
              exp: 'Il détaille un cas d’utilisation dans le temps : dans quel ordre les composants échangent-ils ?',
            },
            {
              t: 'multi',
              q: 'Quels sont les participants du diagramme de séquence du projet ?',
              a: ['Front', 'Express', 'Auth', 'DB', 'Vercel'],
              c: [0, 1, 2, 3],
              exp: 'Quatre participants : Front, Express, Auth, DB — plus les acteurs Utilisateur et Admin.',
            },
            {
              t: 'qcm',
              q: 'Quelle requête part du front quand l’utilisateur saisit un message ?',
              a: [
                'GET /api/messages',
                'POST /api/messages (Bearer token)',
                'POST /api/admin/approve/:id',
                'PUT /api/messages/:id',
              ],
              c: 1,
              exp: 'POST /api/messages avec le Bearer token.',
            },
            {
              t: 'qcm',
              q: 'Quel middleware est déclenché sur POST /api/messages ?',
              a: ['requireAdmin', 'requireAuth', 'rateLimit', 'cors'],
              c: 1,
              exp: 'requireAuth vérifie le token.',
            },
            {
              t: 'qcm',
              q: 'Que fait requireAuth en base ?',
              a: [
                'Un INSERT dans sessions',
                'Un SELECT session + user, puis pose req.user',
                'Un UPDATE du rôle',
                'Rien : il lit seulement le token',
              ],
              c: 1,
              exp: 'requireAuth vérifie le token, fait un SELECT session + user, récupère l’utilisateur et pose req.user.',
            },
            {
              t: 'qcm',
              q: 'Avec quel status le message est-il inséré ?',
              a: ["'approved'", "'pending'", "'rejected'", 'NULL'],
              c: 1,
              exp: "INSERT message (status = 'pending').",
            },
            {
              t: 'qcm',
              q: 'Quel code HTTP le serveur renvoie-t-il après l’insertion ?',
              a: ['200 OK', '201 Created', '204 No Content', '302 Found'],
              c: 1,
              exp: '201 — en attente de validation.',
            },
            {
              t: 'vf',
              q: 'Après l’insertion, le message est visible du public.',
              c: false,
              exp: 'Le message existe en base mais reste invisible au public tant qu’un administrateur n’a pas tranché.',
            },
            {
              t: 'ordre',
              q: 'Remets le scénario complet dans l’ordre.',
              items: [
                'L’utilisateur saisit un message',
                'POST /api/messages (Bearer token)',
                'requireAuth vérifie le token et pose req.user',
                "INSERT message (status = 'pending')",
                '201 en attente de validation',
                'L’admin ouvre l’espace admin',
                'POST /api/admin/approve/:id (Bearer token)',
                'requireAdmin vérifie le rôle',
                "UPDATE message SET status = 'approved'",
                '200 message publié',
              ],
              exp: 'C’est le scénario le plus représentatif du projet : il traverse les quatre couches et implique les deux rôles.',
            },
          ],
        },
        {
          id: 'u8l2',
          title: 'Use case ou séquence ?',
          icon: '⚖️',
          questions: [
            {
              t: 'qcm',
              q: 'Quelle route l’administrateur appelle-t-il pour publier ?',
              a: [
                'POST /api/admin/approve/:id (Bearer token)',
                'PUT /api/messages/:id/status',
                'POST /api/messages/approve',
                'GET /api/admin/pending',
              ],
              c: 0,
              exp: 'POST /api/admin/approve/:id, protégée par requireAdmin.',
            },
            {
              t: 'qcm',
              q: 'Que vérifie requireAdmin ?',
              a: ['Le token seulement', 'Le rôle', 'L’adresse IP', 'La date de session'],
              c: 1,
              exp: 'requireAdmin vérifie le rôle : rôle admin OK, puis UPDATE.',
            },
            {
              t: 'paires',
              q: 'Cas d’utilisation ou séquence ? Associe.',
              pairs: [
                ['Qui peut faire quoi ?', 'Cas d’utilisation'],
                ['Dans quel ordre ça se passe ?', 'Séquence'],
                ['Fonctionnelle et statique', 'Cas d’utilisation'],
                ['Technique et temporelle', 'Séquence'],
              ],
              exp: 'Le cas d’utilisation montre les acteurs et les services ; la séquence montre les composants et les messages échangés.',
            },
            {
              t: 'qcm',
              q: 'Quelle est la portée d’un diagramme de séquence ?',
              a: ['Tout le système', 'Un seul scénario', 'Une seule table', 'Un seul acteur'],
              c: 1,
              exp: 'Séquence : un seul scénario. Cas d’utilisation : tout le système.',
            },
            {
              t: 'qcm',
              q: 'Que faut-il corriger dans le fichier diagram-de-sequence.png du projet ?',
              a: [
                'Il affiche encore INSERT message (approved = 0) et UPDATE message SET approved = 1',
                'Il inverse l’ordre des acteurs',
                'Il oublie le middleware requireAuth',
                'Il montre une base PostgreSQL',
              ],
              c: 0,
              exp: 'Ce champ booléen n’existe pas dans db.js : la vraie colonne est status, avec trois valeurs. La version corrigée est celle de la fiche.',
            },
            {
              t: 'qcm',
              q: 'Pourquoi ce scénario est-il le plus représentatif du projet ?',
              a: [
                'Parce qu’il est le plus rapide à exécuter',
                'Parce qu’il traverse les quatre couches et implique les deux rôles',
                'Parce qu’il ne touche pas à la base',
                'Parce qu’il est entièrement automatisé',
              ],
              c: 1,
              exp: 'Phrase à dire en le commentant : il traverse les quatre couches et implique les deux rôles.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u9',
      title: 'CI/CD',
      subtitle: 'La CI vérifie, le CD livre ou déploie',
      color: '#14b8a6',
      icon: '🔁',
      lessons: [
        {
          id: 'u9l1',
          title: 'Le vocabulaire',
          icon: '📚',
          questions: [
            {
              t: 'qcm',
              q: 'Quelle formule résume la distinction CI / CD ?',
              a: [
                'La CI déploie, le CD teste',
                'La CI vérifie, le CD livre ou déploie',
                'La CI et le CD font la même chose',
                'La CI compile, le CD documente',
              ],
              c: 1,
              exp: 'Le vocabulaire doit être précis : la CI vérifie, le CD livre ou déploie.',
            },
            {
              t: 'qcm',
              q: 'Quand la CI est-elle déclenchée ?',
              a: [
                'À chaque push ou pull request',
                'Une fois par semaine',
                'Uniquement avant la mise en production',
                'À la demande, manuellement',
              ],
              c: 0,
              exp: 'Déclenchée à chaque push ou pull request : récupère le code, installe, contrôle la qualité, lance les tests.',
            },
            {
              t: 'qcm',
              q: 'Quel est le but de l’intégration continue ?',
              a: [
                'Automatiser la mise en ligne',
                'Détecter une régression tout de suite',
                'Réduire le coût d’hébergement',
                'Générer la documentation',
              ],
              c: 1,
              exp: 'But de la CI : détecter une régression tout de suite.',
            },
            {
              t: 'qcm',
              q: 'Continuous delivery, c’est…',
              a: [
                'Chaque modification part automatiquement en production',
                'Le livrable est prêt à être déployé ; une approbation humaine peut rester nécessaire',
                'Les tests sont lancés à chaque commit',
                'Le code est relu par un pair',
              ],
              c: 1,
              exp: 'But : rendre la livraison fiable et répétable.',
            },
            {
              t: 'qcm',
              q: 'Continuous deployment, c’est…',
              a: [
                'Chaque modification validée part automatiquement en production',
                'Un livrable prêt mais non déployé',
                'Un déploiement manuel planifié',
                'Une sauvegarde automatique',
              ],
              c: 0,
              exp: 'Vercel redéploie depuis le dépôt Git. But : automatiser aussi la mise en ligne.',
            },
            {
              t: 'paires',
              q: 'Associe chaque pratique à son but.',
              pairs: [
                ['CI — intégration continue', 'Détecter une régression tout de suite'],
                ['CD — continuous delivery', 'Rendre la livraison fiable et répétable'],
                ['CD — continuous deployment', 'Automatiser aussi la mise en ligne'],
              ],
              exp: 'Trois pratiques, trois buts distincts.',
            },
            {
              t: 'qcm',
              q: 'La réponse courte à « qui fait quoi dans votre chaîne ? » :',
              a: [
                '« GitHub Actions déploie et Vercel teste. »',
                '« GitHub Actions est le gardien de la qualité. Vercel est le mécanisme de publication. »',
                '« Tout est manuel. »',
                '« Vercel fait la CI et le CD. »',
              ],
              c: 1,
              exp: 'Formule à retenir telle quelle.',
            },
          ],
        },
        {
          id: 'u9l2',
          title: 'Le pipeline réel',
          icon: '🛠️',
          questions: [
            {
              t: 'qcm',
              q: 'Qu’est-ce qui déclenche le pipeline du projet ?',
              a: [
                'Un push ou une pull request sur main',
                'Un tag de version',
                'Une action manuelle dans Vercel',
                'Un cron quotidien',
              ],
              c: 0,
              exp: 'Déclencheur : push ou pull request sur main.',
            },
            {
              t: 'ordre',
              q: 'Remets les étapes du pipeline dans l’ordre.',
              items: [
                'Checkout du code',
                'Installer Node.js 20',
                'npm ci',
                'npm run lint — ESLint',
                'npm run format:check — Prettier',
                'npm test — 15 tests',
              ],
              exp: 'Le pipeline compte 5 étapes : checkout, Node, install, qualité, tests.',
            },
            {
              t: 'qcm',
              q: 'Quelle version de Node.js le pipeline installe-t-il ?',
              a: ['Node.js 18', 'Node.js 20', 'Node.js 22', 'Node.js 24'],
              c: 1,
              exp: 'Le workflow installe Node.js 20.',
            },
            {
              t: 'qcm',
              q: 'Pourquoi npm ci plutôt que npm install en CI ?',
              a: [
                'Parce qu’il est plus court à écrire',
                'Parce qu’il installe à partir du fichier de verrouillage, de façon reproductible',
                'Parce qu’il ignore les dépendances de développement',
                'Parce qu’il met à jour les dépendances',
              ],
              c: 1,
              exp: 'npm ci est l’étape d’installation du pipeline : une installation propre et reproductible.',
            },
            {
              t: 'multi',
              q: 'Quels contrôles de qualité le pipeline exécute-t-il ?',
              a: ['npm run lint (ESLint)', 'npm run format:check (Prettier)', 'npm test', 'npm audit', 'npm run build'],
              c: [0, 1, 2],
              exp: 'Qualité : ESLint et Prettier, puis les tests.',
            },
            {
              t: 'qcm',
              q: 'Combien de tests le pipeline exécute-t-il ?',
              a: ['7 tests', '12 tests', '15 tests', '20 tests'],
              c: 2,
              exp: 'npm test — 15 tests. Soit 8 tests d’intégration et 7 tests unitaires.',
            },
            {
              t: 'qcm',
              q: 'Que se passe-t-il si le résultat est vert ?',
              a: [
                'Fusion autorisée, Vercel publie',
                'Le déploiement est bloqué en attente',
                'Rien, il faut relancer manuellement',
                'Les tests sont rejoués',
              ],
              c: 0,
              exp: 'Vert : fusion autorisée, Vercel publie. Rouge : fusion signalée en erreur, il faut lire le journal et corriger.',
            },
            {
              t: 'ordre',
              q: 'Un test échoue en CI. Remets ta réaction dans l’ordre.',
              items: [
                'Le job passe au rouge, la PR est signalée en erreur',
                'Lire le journal du job',
                'Reproduire en local avec npm test',
                'Corriger le test ou la règle',
                'Repousser le commit',
              ],
              exp: 'C’est la réponse attendue à « que se passe-t-il si un test échoue en CI ? ».',
            },
            {
              t: 'multi',
              q: 'Quels scripts npm le projet expose-t-il ?',
              a: ['setup', 'init-db', 'test', 'deploy', 'migrate'],
              c: [0, 1, 2, 3],
              exp: 'Scripts npm : setup, init-db, test, deploy.',
            },
          ],
        },
        {
          id: 'u9l3',
          title: 'Automatisé ou manuel ?',
          icon: '🤖',
          questions: [
            {
              t: 'multi',
              q: 'Qu’est-ce qui est automatisé dans la chaîne ?',
              a: [
                'GitHub Actions : installation, qualité et tests à chaque push ou PR',
                'Vercel : build et publication depuis la branche principale',
                'predeploy : tests relancés avant un déploiement CLI',
                'La relecture humaine avant fusion',
                'La restauration de base',
              ],
              c: [0, 1, 2],
              exp: 'Les trois premiers sont automatisés ; la relecture et les migrations restent manuelles.',
            },
            {
              t: 'multi',
              q: 'Qu’est-ce qui reste manuel ?',
              a: [
                'Relecture humaine avant fusion de la pull request',
                'Migrations et restauration de base',
                'Tests visuels de bout en bout dans un navigateur',
                'Verrouillage strict du déploiement sur CI verte — à finaliser',
                'Le lancement des tests unitaires',
              ],
              c: [0, 1, 2, 3],
              exp: 'Les tests unitaires sont automatisés par GitHub Actions ; le reste de cette liste est assumé comme manuel.',
            },
            {
              t: 'qcm',
              q: 'Quelle posture assumer sur l’automatisation ?',
              a: [
                '« Tout doit être automatisé, sinon ce n’est pas professionnel. »',
                '« Je n’automatise pas aveuglément. J’automatise les répétitions vérifiables et je conserve une décision humaine pour les choix sensibles. »',
                '« L’automatisation coûte trop cher pour un projet de formation. »',
                '« J’automatiserai plus tard. »',
              ],
              c: 1,
              exp: 'C’est l’honnêteté qui joue en ta faveur devant le jury.',
            },
            {
              t: 'qcm',
              q: '« Votre CI bloque-t-elle vraiment le déploiement ? »',
              a: [
                '« Oui, techniquement, rien ne peut être publié si la CI est rouge. »',
                '« La CI signale la fusion en erreur si une étape échoue, et Vercel publie depuis main. Le verrouillage strict est identifié comme l’évolution suivante. »',
                '« Non, la CI ne sert à rien dans mon projet. »',
                '« Je ne sais pas. »',
              ],
              c: 1,
              exp: 'Mieux vaut le dire que se faire prendre en défaut : le verrouillage strict est l’évolution suivante, pas l’état actuel.',
            },
            {
              t: 'vf',
              q: 'Dans le projet, interdire techniquement la publication tant que la chaîne n’est pas verte est déjà en place.',
              c: false,
              exp: 'Non : c’est identifié comme l’évolution suivante. À dire franchement.',
            },
            {
              t: 'qcm',
              q: 'Que fait le script predeploy ?',
              a: [
                'Il relance les tests avant un déploiement CLI',
                'Il crée la base de données',
                'Il génère la documentation',
                'Il publie sur GitHub',
              ],
              c: 0,
              exp: 'predeploy : tests relancés avant un déploiement en ligne de commande.',
            },
            {
              t: 'paires',
              q: 'Automatisé ou manuel ? Associe.',
              pairs: [
                ['Qualité et tests à chaque push', 'Automatisé'],
                ['Build et publication depuis main', 'Automatisé'],
                ['Relecture avant fusion', 'Manuel'],
                ['Migrations et restauration de base', 'Manuel'],
              ],
              exp: 'Savoir tracer la frontière est exactement ce que le jury cherche à entendre.',
            },
          ],
        },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u10',
      title: 'Chiffres & pièges',
      subtitle: 'Ce qui doit sortir sans hésiter',
      color: '#a855f7',
      icon: '🎯',
      lessons: [
        {
          id: 'u10l1',
          title: 'Les chiffres',
          icon: '🔢',
          questions: [
            {
              t: 'qcm',
              q: 'Combien de tests, et comment se répartissent-ils ?',
              a: [
                '15 sur 15 — 8 d’intégration, 7 unitaires',
                '7 sur 7 — 4 d’intégration, 3 unitaires',
                '15 sur 15 — tous unitaires',
                '12 sur 12 — 6 et 6',
              ],
              c: 0,
              exp: '15 sur 15 : 8 tests d’intégration et 7 tests unitaires. C’est ce chiffre qui tranche la contradiction entre les deux dossiers.',
            },
            {
              t: 'qcm',
              q: 'Combien d’étapes compte le pipeline ?',
              a: ['3 étapes', '4 étapes', '5 étapes', '6 étapes'],
              c: 2,
              exp: '5 étapes : checkout, Node, install, qualité, tests.',
            },
            {
              t: 'qcm',
              q: 'Combien d’acteurs, et lesquels ?',
              a: [
                '2 — membre et administrateur',
                '3 — visiteur, membre, administrateur',
                '4 — visiteur, membre, modérateur, administrateur',
                '3 — front, back, base',
              ],
              c: 1,
              exp: '3 acteurs : visiteur, membre, administrateur.',
            },
            {
              t: 'multi',
              q: 'Quelles sont les quatre couches de l’application ?',
              a: ['Présentation', 'API', 'Métier', 'Données', 'Déploiement'],
              c: [0, 1, 2, 3],
              exp: '4 couches : présentation, API, métier, données.',
            },
            {
              t: 'multi',
              q: 'Quelles sont les quatre tables ?',
              a: ['users', 'messages', 'favoris', 'sessions', 'roles'],
              c: [0, 1, 2, 3],
              exp: '4 tables : users, messages, favoris, sessions.',
            },
            {
              t: 'qcm',
              q: 'Combien de statuts un message peut-il prendre ?',
              a: ['2 statuts', '3 statuts', '4 statuts', 'Autant que nécessaire'],
              c: 1,
              exp: '3 statuts : pending, approved, rejected.',
            },
            {
              t: 'qcm',
              q: 'Quel est le résultat ESLint / Prettier revendiqué ?',
              a: [
                '0 erreur, formatage conforme',
                'Quelques avertissements tolérés',
                'Non mesuré',
                'Uniquement ESLint, sans Prettier',
              ],
              c: 0,
              exp: '0 erreur, formatage conforme.',
            },
            {
              t: 'saisie',
              q: 'Combien de tests d’intégration le projet compte-t-il ?',
              accept: ['8', 'huit'],
              exp: '8 tests d’intégration, complétés par 7 tests unitaires — 15 au total.',
            },
          ],
        },
        {
          id: 'u10l2',
          title: 'Les pièges classiques',
          icon: '🪤',
          questions: [
            {
              t: 'qcm',
              q: 'Piège n°1 : confondre Merise et UML. Que répondre ?',
              a: [
                '« Ce sont deux notations équivalentes. »',
                '« Merise décrit ce que le système mémorise, UML décrit ce qu’il fait. Mon projet utilise les deux. »',
                '« J’ai choisi UML parce que Merise est dépassée. »',
                '« Merise sert au front, UML au back. »',
              ],
              c: 1,
              exp: 'Il faut savoir dire lequel sert à quoi.',
            },
            {
              t: 'qcm',
              q: 'Piège n°2 : une bulle nommée comme une route. Comment le corriger ?',
              a: [
                'En renommant la bulle avec un service rendu, par exemple « Proposer un message »',
                'En supprimant la bulle',
                'En déplaçant l’acteur à l’intérieur du système',
                'En ajoutant la table concernée',
              ],
              c: 0,
              exp: 'Un cas d’utilisation ne contient ni tables, ni routes, ni classes.',
            },
            {
              t: 'qcm',
              q: 'Piège n°3 : le booléen approved. Que faut-il dire ?',
              a: [
                '« Le champ approved a été renommé status. »',
                '« Le booléen ne pouvait pas coder le rejet : il a été remplacé par status, contrôlé par un CHECK sur trois valeurs. Les anciens diagrammes étaient en avance sur le code, je les ai corrigés. »',
                '« C’est une erreur de SQLite. »',
                '« Les deux existent dans la base. »',
              ],
              c: 1,
              exp: 'Assumer la correction et l’expliquer par la règle métier vaut mieux que la masquer.',
            },
            {
              t: 'multi',
              q: 'Quels documents du projet contenaient encore l’ancien booléen ?',
              a: [
                'Les trois diagrammes MCD / MLD / MPD précédents',
                'Le fichier diagram-de-sequence.png',
                'Le fichier db.js',
                'Le workflow ci.yml',
              ],
              c: [0, 1],
              exp: 'db.js et le workflow étaient corrects : ce sont les diagrammes qui affichaient approved.',
            },
            {
              t: 'qcm',
              q: 'Piège n°4 : « votre CI verrouille-t-elle la production ? »',
              a: [
                'Affirmer que oui pour rassurer',
                'Dire honnêtement que la CI signale l’erreur, que Vercel publie depuis main, et que le verrouillage strict est l’évolution suivante',
                'Éviter la question',
                'Répondre que Vercel s’en charge',
              ],
              c: 1,
              exp: 'Mieux vaut le dire que se faire prendre en défaut.',
            },
            {
              t: 'vf',
              q: 'Le diagramme de séquence est le bon endroit pour montrer les cardinalités.',
              c: false,
              exp: 'Non : les cardinalités appartiennent au MCD. La séquence montre les composants et les messages échangés dans le temps.',
            },
            {
              t: 'qcm',
              q: 'Phrase de conclusion sur l’articulation des deux méthodes :',
              a: [
                '« Merise décrit les données (MCD/MLD/MPD). UML décrit le comportement (cas d’utilisation, séquence). »',
                '« J’ai utilisé UML parce que c’est un standard international. »',
                '« Merise m’a suffi pour tout modéliser. »',
                '« Les deux méthodes font double emploi. »',
              ],
              c: 0,
              exp: 'C’est la phrase de clôture des deux fiches.',
            },
          ],
        },
      ],
    },
  ],
};

/* Index à plat : utile pour le déblocage séquentiel et le renforcement. */
const FLAT_LESSONS = [];
COURSE.units.forEach((u) => {
  u.lessons.forEach((l) => {
    FLAT_LESSONS.push({ ...l, unitId: u.id, unitTitle: u.title, color: u.color });
  });
});

const LESSON_BY_ID = Object.fromEntries(FLAT_LESSONS.map((l) => [l.id, l]));
const TOTAL_QUESTIONS = FLAT_LESSONS.reduce((n, l) => n + l.questions.length, 0);
